In [1]:
############  PANDAS  ############

In [2]:
import numpy as np
import pandas as pd

In [6]:
#dataframe
df = pd.DataFrame(np.arange(1,21).reshape(5,4), index=['r1','r2','r3','r4','r5'], columns=['c1','c2','c3','c4'])

In [7]:
df.head()

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [8]:
# export data
df.to_csv('Demo.csv')

In [10]:
df.loc['r1']

c1    1
c2    2
c3    3
c4    4
Name: r1, dtype: int32

In [11]:
type(df.loc['r1'])

pandas.core.series.Series

In [14]:
df.iloc[1:4, :]

c1  c2  c3  c4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16

In [15]:
type(df.iloc[1:4, :])

pandas.core.frame.DataFrame

In [16]:
df.iloc[0:2,0:1]

c1
r1   1
r2   5

In [17]:
type(df.iloc[0:2,0:1])

pandas.core.frame.DataFrame

In [18]:
df.iloc[0:2,0]

r1    1
r2    5
Name: c1, dtype: int32

In [19]:
type(df.iloc[0:2,0])

pandas.core.series.Series

In [20]:
# convert DataFrame into Array
df.iloc[:,:].values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [21]:
df.iloc[:,:].values.shape

(5, 4)

In [22]:
arr = df.iloc[:,:].values

In [23]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [24]:
# check null 
df.isnull()

c1     c2     c3     c4
r1  False  False  False  False
r2  False  False  False  False
r3  False  False  False  False
r4  False  False  False  False
r5  False  False  False  False

In [25]:
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [27]:
#check one element how many time it present in a col
df['c2'].value_counts()

2     1
6     1
10    1
14    1
18    1
Name: c2, dtype: int64

In [28]:

df['c1'].unique()

array([ 1,  5,  9, 13, 17])

In [29]:
df[['c2','c3']]

c2  c3
r1   2   3
r2   6   7
r3  10  11
r4  14  15
r5  18  19

In [31]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
