In [1]:
############  PANDAS  ############

In [73]:
import numpy as np
import pandas as pd
from io import StringIO, BytesIO

In [74]:
#dataframe
df = pd.DataFrame(np.arange(1,21).reshape(5,4), index=['r1','r2','r3','r4','r5'], columns=['c1','c2','c3','c4'])

In [75]:
df.head()

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [5]:
# export data
df.to_csv('Demo.csv')

In [6]:
df.loc['r1']

c1    1
c2    2
c3    3
c4    4
Name: r1, dtype: int32

In [7]:
type(df.loc['r1'])

pandas.core.series.Series

In [8]:
df.iloc[1:4, :]

c1  c2  c3  c4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16

In [9]:
type(df.iloc[1:4, :])

pandas.core.frame.DataFrame

In [10]:
df.iloc[0:2,0:1]

c1
r1   1
r2   5

In [11]:
type(df.iloc[0:2,0:1])

pandas.core.frame.DataFrame

In [12]:
df.iloc[0:2,0]

r1    1
r2    5
Name: c1, dtype: int32

In [13]:
type(df.iloc[0:2,0])

pandas.core.series.Series

In [14]:
# convert DataFrame into Array
df.iloc[:,:].values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
df.iloc[:,:].values.shape

(5, 4)

In [16]:
arr = df.iloc[:,:].values

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [18]:
# check null 
df.isnull()

c1     c2     c3     c4
r1  False  False  False  False
r2  False  False  False  False
r3  False  False  False  False
r4  False  False  False  False
r5  False  False  False  False

In [19]:
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [20]:
#check one element how many time it present in a col
df['c2'].value_counts()

2     1
6     1
10    1
14    1
18    1
Name: c2, dtype: int64

In [21]:

df['c1'].unique()

array([ 1,  5,  9, 13, 17])

In [22]:
df[['c2','c3']]

c2  c3
r1   2   3
r2   6   7
r3  10  11
r4  14  15
r5  18  19

In [23]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [24]:
df = pd.read_csv('mercedesbenz.csv')

In [25]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [27]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [28]:
# Note: I have created demo.csv separated by cemi colon
df_demo = pd.read_csv('Demo.csv', sep=';')

In [29]:
df_demo

,c1,c2,c3,c4
0      r1,1,2,3,4
1      r2,5,6,7,8
2   r3,9,10,11,12
3  r4,13,14,15,16
4  r5,17,18,19,20

In [30]:
# get unnique category counts
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [31]:
# In y column, wherever value > 100, fetch the value
df[df['y'] > 100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [32]:
data = ('column1,column2,column3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

In [33]:
type(data)

str

In [34]:
pd.read_csv(StringIO(data))

column1 column2  column3
0       x       y        1
1       a       b        2
2       c       d        3

In [35]:
# Read from specific columns
df = pd.read_csv(StringIO(data), usecols=['column1','column3'])

In [36]:
df

column1  column3
0       x        1
1       a        2
2       c        3

In [37]:
df.to_csv('Demo2.csv')

In [38]:
# add another data
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [39]:
type(data)

str

In [40]:
df = pd.read_csv(StringIO(data), dtype=object)

In [41]:
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [42]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [43]:
df['a'][1]

'5'

In [44]:
# see I have added 19 at last to perform some operation
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11, 19')

In [45]:
df = pd.read_csv(StringIO(data), dtype=int)

In [46]:
df

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  19

In [47]:
df = pd.read_csv(StringIO(data), dtype=float)

In [48]:
df

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  19.0

In [49]:
# specify different data type to different column
df = pd.read_csv(StringIO(data), dtype={'b':str, 'd':float, 'c':'Int32'})

In [50]:
df

a   b   c     d
0  1   2   3   4.0
1  5   6   7   8.0
2  9  10  11  19.0

In [51]:
type(df['a'][0])

numpy.int64

In [52]:
type(df['b'][1])

str

In [53]:
type(df['c'][2])

numpy.int32

In [54]:
type(df['d'][2])

numpy.float64

In [55]:
# check data type of each column
df.dtypes

a      int64
b     object
c      Int32
d    float64
dtype: object

In [56]:
# index_col
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [57]:
type(StringIO(data))

_io.StringIO

In [58]:
# index_col helps to makes column as index
# here you can make any column as index
pd.read_csv(StringIO(data), index_col=1)

index    b     c
a                       
apple       4  bat   5.7
orange      8  cow  10.0

In [59]:

pd.read_csv(StringIO(data), index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [60]:
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [61]:
pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [62]:
pd.read_csv(StringIO(data), index_col = False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [63]:
data = ('a,b,c\n'
           '4,apple,bat,\n'
            '8,orange,cow,')

In [64]:
pd.read_csv(StringIO(data), usecols=['a','c'], index_col=False)

a    c
0  4  bat
1  8  cow

In [65]:
## Quoting and Escape Characters¶. Very useful in NLP

data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [66]:
pd.read_csv(StringIO(data), escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [67]:
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')

HTTPError: HTTP Error 403: Forbidden

In [ ]:

# Pandas-Reading JSON,Reading HTML, Read PICKLE, Read EXCEL Files

In [ ]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
pd.read_json(Data)

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [ ]:
df

In [ ]:

df.to_csv('wine.csv')

In [ ]:
df.head()

In [ ]:
#convert dataframe into json
df.to_json()

In [ ]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df1 = pd.read_json(Data)

In [ ]:
df1

In [ ]:
df1.to_json()

In [ ]:
df1.to_json(orient='records')

In [ ]:
df.head()

In [ ]:
df.head().to_json()

In [ ]:
df.head().to_json(orient="records")

In [ ]:
######## READING HTML CONTENT  ########

In [76]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
dfs = pd.read_html(url)

ValueError: No tables found

In [71]:
dfs[0]

NameError: name 'dfs' is not defined