In [1]:
import numpy as np

In [2]:
list1 = [0,1,2,3,4,5]
arr = np.array(list1)

In [5]:
print(type(list1))   #<class 'list'>
print(type(arr))     #<class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
row_col = arr.shape # arr.shape will show no of row and no of col like this -> (row, col)

In [12]:
print(row_col) 

(6,)


In [13]:
list1 = [0,1,2,3,4,5]
list2 = [0,1,2,3,4,5]
list3 = [0,1,2,3,4,5]

arr = np.array([list1, list2, list3])

In [14]:
arr.shape

(3, 6)

In [15]:
arr

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [20]:
# reshape - Returns an array containing the same data with a new shape.
arr.reshape(9, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [18]:
# note: if I write at row 1, it will not 1D array, it will be a multi-dimension array
arr.reshape(1, 18)

array([[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]])

In [22]:
arr.shape

(3, 6)

In [23]:
############## INDEX ###################

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [30]:
arr[3]

4

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
arr = arr.reshape(3,5)

In [34]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
# access all element
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [37]:
arr[0:2,2:4]

array([[3, 4],
       [8, 9]])

In [40]:
arr[1:3, 2:4]

array([[ 8,  9],
       [13, 14]])

In [41]:
arr[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [50]:
'''
The numpy.arange() function in Python is used to create a sequence of numbers within a specified range.
It returns an array with evenly spaced values between a given start and end value, 
incrementing by a specified step size.

'''

arr = np.arange(1, 1300, step=3)
print(arr)

[   1    4    7   10   13   16   19   22   25   28   31   34   37   40
   43   46   49   52   55   58   61   64   67   70   73   76   79   82
   85   88   91   94   97  100  103  106  109  112  115  118  121  124
  127  130  133  136  139  142  145  148  151  154  157  160  163  166
  169  172  175  178  181  184  187  190  193  196  199  202  205  208
  211  214  217  220  223  226  229  232  235  238  241  244  247  250
  253  256  259  262  265  268  271  274  277  280  283  286  289  292
  295  298  301  304  307  310  313  316  319  322  325  328  331  334
  337  340  343  346  349  352  355  358  361  364  367  370  373  376
  379  382  385  388  391  394  397  400  403  406  409  412  415  418
  421  424  427  430  433  436  439  442  445  448  451  454  457  460
  463  466  469  472  475  478  481  484  487  490  493  496  499  502
  505  508  511  514  517  520  523  526  529  532  535  538  541  544
  547  550  553  556  559  562  565  568  571  574  577  580  583  586
  589 

In [58]:
'''
The numpy.linspace() function in Python is used to create an array of evenly spaced values over a specified range. 
It returns an array with a specified number of elements, 
evenly distributed between a start and end value.

'''
np.linspace(1, 19, 80)

array([ 1.        ,  1.2278481 ,  1.4556962 ,  1.6835443 ,  1.91139241,
        2.13924051,  2.36708861,  2.59493671,  2.82278481,  3.05063291,
        3.27848101,  3.50632911,  3.73417722,  3.96202532,  4.18987342,
        4.41772152,  4.64556962,  4.87341772,  5.10126582,  5.32911392,
        5.55696203,  5.78481013,  6.01265823,  6.24050633,  6.46835443,
        6.69620253,  6.92405063,  7.15189873,  7.37974684,  7.60759494,
        7.83544304,  8.06329114,  8.29113924,  8.51898734,  8.74683544,
        8.97468354,  9.20253165,  9.43037975,  9.65822785,  9.88607595,
       10.11392405, 10.34177215, 10.56962025, 10.79746835, 11.02531646,
       11.25316456, 11.48101266, 11.70886076, 11.93670886, 12.16455696,
       12.39240506, 12.62025316, 12.84810127, 13.07594937, 13.30379747,
       13.53164557, 13.75949367, 13.98734177, 14.21518987, 14.44303797,
       14.67088608, 14.89873418, 15.12658228, 15.35443038, 15.58227848,
       15.81012658, 16.03797468, 16.26582278, 16.49367089, 16.72

In [75]:
arr2

array([0, 1, 2, 3, 4, 5])

In [73]:
my_list = [1, 2, 3]
print(my_list)  # Output: [1, 2, 3]

my_list[1] = 5
print(my_list)  # Output: [1, 5, 3]
my_list = [2,3,4]
print(my_list)

[1, 2, 3]
[1, 5, 3]
[2, 3, 4]


In [82]:
list4 = [2,34,45,5,6,456,56,4,34,23,1,212,4]

In [83]:
arr2 = np.array(list4)

In [84]:
arr2

array([  2,  34,  45,   5,   6, 456,  56,   4,  34,  23,   1, 212,   4])

In [86]:
arr3 = np.array(my_list)
arr3

array([2, 3, 4])

In [91]:
arr3 = arr

In [93]:
arr3[2:] = 999

############          NOTE         ############
 
# in python, array is reference type,
# [i.e if you previously assigned like this arr3 = arr 
#  and if you change arr3[xyz:] = abcd, it will be changed for both array]

In [94]:
arr3

array([  0,   1, 999, 999, 999, 999])

In [95]:
arr

array([  0,   1, 999, 999, 999, 999])

In [97]:
print(arr)
print(arr3)

[  0   1 999 999 999 999]
[  0   1 999 999 999 999]


In [101]:
arr3 = arr.copy() # array.copy create another memory space. So arr and arr3 referring to diff memory location

In [102]:
arr3[1:] = 321

In [103]:
print(arr)
print(arr3)

[  0   1 999 999 999 999]
[  0 321 321 321 321 321]


In [105]:
#      SOME CONDITION VERY USEFUL IN EXPLORATORY DATA ANALYSIS

In [113]:
val = 32
print(arr)
print(arr < val)
print(arr * val)
print(arr % val)
print(arr / val)

[  0   1 999 999 999 999]
[ True  True False False False False]
[    0    32 31968 31968 31968 31968]
[0 1 7 7 7 7]
[ 0.       0.03125 31.21875 31.21875 31.21875 31.21875]


In [114]:
arr[arr>23]

array([999, 999, 999, 999])

In [117]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [119]:
np.ones((4, 9),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [124]:
# RANDOM DISTRIBUTING
np.random.rand(4, 5)

array([[0.33832321, 0.38486738, 0.38975765, 0.66569286, 0.67370979],
       [0.82267643, 0.70097604, 0.18608622, 0.40731795, 0.66403776],
       [0.78146255, 0.82365054, 0.08588964, 0.89869933, 0.7366052 ],
       [0.29849558, 0.13387053, 0.91332025, 0.04061144, 0.95539231]])

In [129]:
arr4 = np.random.randn(3,4)
arr4

array([[ 2.00909088, -0.68508187,  0.35729548,  0.13767198],
       [-0.63497125,  0.09538753, -1.01329913,  0.05547266],
       [ 1.21462773, -0.70650582, -1.08461263,  0.53088929]])

In [131]:
np.random.randint(43, 99, 24).reshape(3,8)

array([[64, 47, 84, 44, 71, 60, 60, 49],
       [85, 96, 87, 86, 89, 89, 46, 92],
       [74, 52, 46, 54, 78, 72, 59, 91]])

In [134]:
np.random.random_sample((2,6)) # Return random floats in the half-open interval [0.0, 1.0).

array([[0.43060531, 0.2529111 , 0.70367929, 0.52261527, 0.06969343,
        0.01740135],
       [0.63421127, 0.10801462, 0.43518416, 0.26343347, 0.22515548,
        0.85135097]])